<aside class="job-links">
    <div class="application-page-logo">
        <img src="images/logo.png" class="logo-image" alt="Company Logo">
    </div>
    <ul>
        <li><a href="index.php" class="nav-link">Home</a></li>
        <li><a href="jobs.php" class="nav-link">Jobs</a></li>
        <li><a href="apply.php" class="nav-link">Apply</a></li>
        <li><a href="manage.php" class="nav-link">Manage</a></li>
        <li><a href="about.php" class="nav-link">About Us</a></li>
    </ul>
</aside>