<footer class="incl">
    <p>&copy; 2025 Tech Careers Inc. All rights reserved.</p>
    <nav>
        <a href="https://id.atlassian.com/invite/p/jira-software?id=vogG_QdzQOGIyAK_Hb6ixg" target="_blank">Jira invite link</a> |
        <a href="https://lsvj.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog" target="_blank">Jira project link</a> |
        <a href="https://github.com/JordanThomasButler/LVSJ-GroupProj" target="_blank">GitHub Project File</a>    
        <p class="bottom-text">Contact us at <a href="mailto:info@yourcompany.com.au">info@Techcareers.com.au</a></p>
    </nav>
</footer>

</body>
</html>